name: servant-avro
version: 0.1.0.0
synopsis: Avro content type for Servant
description: This package lets Servant use Avro for encoding request data
maintainer: Jesse Kempf
github: doublecrowngaming/servant-avro
license: BSD3
category: Servant, Web

ghc-options: -Wall

default-extensions:
- StrictData

dependencies:
  - base >= 4.7 && < 5
  - avro
  - servant

library:
  source-dirs: src
  exposed-modules:
    - Servant.API.ContentTypes.Avro

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - servant-avro
      - servant-client
      - servant-server
      - hspec >=2.0.0
      - http-client
      - QuickCheck
      - text
      - warp
